version: "3"

services:
  tomcat1: &was
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=docker -Dfile.encoding=euc-kr
    build:
      context: .
      args:
        conf: tomcat1/conf
        warpath: tomcat1/webapps/ROOT.war
      dockerfile: ./DockerfileTomcat
    volumes:
      - ./tomcat1/logs/:/usr/local/tomcat/logs/
  tomcat2:
    <<: *was
    build:
      context: .
      args:
        conf: tomcat2/conf
        warpath: tomcat2/webapps/ROOT.war
      dockerfile: ./DockerfileTomcat
    volumes:
      - ./tomcat2/logs/:/usr/local/tomcat/logs/
  nginx:
    build:
      context: .
      dockerfile: ./DockerfileNginx
      args:
        conf: nginx/conf
    ports:
      - "8080:8080"
